### ISSUE TITLE
[建议]希望能自定义音色

### ISSUE THREAD

**Issue by RAINighty** [lvyonghuan/GoATuber#1]
[【AI虚拟主播】sovits+chatglm](https://www.bilibili.com/video/BV1w24y1j7eE/)
希望能自定义音色，使用sovits（或者其他的）自行训练的模型来输出音频

**Comment by lvyonghuan** [comment]
其实当初做分块就是考虑方便加这些功能（
不过电脑不太行，做不了本地的测试，另外最近时间有点紧了，所以暂且放在TODO上
也欢迎pull request，我大概讲讲我的思路，才入门没几个月，多多包涵（
sovits据说是有文成音能力的话，如果可以，在speech模块有一个get_message，在那里有一个if的判断，用来判断使用什么去生成语音。可以在那里加一个else if，对接上sovits的模块。sovits是基于Python的，那就用一个方法去实现go和python的通信。

**Comment by RAINighty** [comment]
> 其实当初做分块就是考虑方便加这些功能（ 不过电脑不太行，做不了本地的测试，另外最近时间有点紧了，所以暂且放在TODO上 也欢迎pull request，我大概讲讲我的思路，才入门没几个月，多多包涵（ sovits据说是有文成音能力的话，如果可以，在speech模块有一个get_message，在那里有一个if的判断，用来判断使用什么去生成语音。可以在那里加一个else if，对接上sovits的模块。sovits是基于Python的，那就用一个方法去实现go和python的通信。

我是个菜鸟来的，所以只能等大佬做了：>
